from scraper.adapters import (
    amazon,
    apple,
    ashby,
    eightfold,
    google,
    greenhouse,
    icims,
    jibe,
    lever,
    meta,
    microsoft,
    oraclehcm,
    smartrecruiters,
    talentbrew,
    workable,
    workday,
)
from scraper.adapters.base import Adapter

ADAPTERS: dict[str, Adapter] = {
    "google": google.fetch,
    "greenhouse": greenhouse.fetch,
    "icims": icims.fetch,
    "jibe": jibe.fetch,
    "talentbrew": talentbrew.fetch,
    "lever": lever.fetch,
    "lever_eu": lever.fetch_eu,
    "meta": meta.fetch,
    "microsoft": microsoft.fetch,
    "amazon": amazon.fetch,
    "apple": apple.fetch,
    "ashby": ashby.fetch,
    "eightfold": eightfold.fetch,
    "eightfold_v2": eightfold.fetch_v2,
    "oraclehcm": oraclehcm.fetch,
    "smartrecruiters": smartrecruiters.fetch,
    "workable": workable.fetch,
    "workday": workday.fetch,
}
